apiVersion: apps/v1
kind: Deployment
metadata:
    name: order-deployment
    labels:
        app: order
spec:
    replicas: 1
    selector:
        matchLabels:
            app: order
    template:
        metadata:
            labels:
                app: order
        spec:
            containers:
                - name: order
                  image: benukapunchihewa/order-service:latest
                  imagePullPolicy: Always
                  resources:
                      requests:
                          memory: "250Mi"
                          cpu: "150m"
                      limits:
                          memory: "500Mi"
                          cpu: "200m"
                  ports:
                      - containerPort: 5001
                  env:
                      - name: MONGO_URL
                        valueFrom:
                            configMapKeyRef:
                                name: order-config
                                key: mongo-url
                      - name: SERVICE_ACCESS_TOKEN
                        valueFrom:
                            configMapKeyRef:
                                name: order-config
                                key: service-access-token
                      - name: AUTH_SERVICE_BASE_URL
                        valueFrom:
                            configMapKeyRef:
                                name: order-config
                                key: auth-service-base-url
                      - name: USER_SERVICE_BASE_URL
                        valueFrom:
                            configMapKeyRef:
                                name: order-config
                                key: user-service-base-url
                      - name: PRODUCT_SERVICE_BASE_URL
                        valueFrom:
                            configMapKeyRef:
                                name: order-config
                                key: product-service-base-url
---
apiVersion: v1
kind: Service
metadata:
    name: order-service
spec:
    selector:
        app: order
    ports:
        - protocol: TCP
          port: 5004
          targetPort: 5001
